### ISSUE TITLE
Standalone executable error on Linux

### ISSUE THREAD

**Issue by EveGayer** [DARIAH-DE/TopicsExplorer#53] opened 2018-06-14 11:38 UTC
```
[1263] Error loading Python lib '/tmp/_MEIcWzU1T/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIcWzU1T/libpython3.6m.so.1.0)
```

on

```
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
```

**Comment by severinsimmler** [comment] 2018-06-14 11:41
Executable built with

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by severinsimmler** [comment] 2018-06-14 14:14
The problem is that we have different C system libraries on two machines. There can sometimes be difficulties when porting a pre-built binary. Either we ensure that we're using a similar environment or you put all dependencies into the binary - this may increase its size significantly.

PyInstaller itself recommends the following:
>  The executable that PyInstaller builds is not fully static, in that it still depends on the system libc. Under Linux, the ABI of GLIBC is backward compatible, but not forward compatible. So if you link against a newer GLIBC, you can't run the resulting executable on an older system. The supplied binary bootloader should work with older GLIBC. However, the libpython.so and other dynamic libraries still depends on the newer GLIBC. The solution is to compile the Python interpreter with its modules (and also probably bootloader) on the oldest system you have around, so that it gets linked with the oldest version of GLIBC.

So we should first try if the current version runs on another machine with Ubuntu 18.04 (@sinabock  already requested). Then we should create the executable on an older Ubuntu (Debian?) running machine (14.04 LTS is fully supported until April 2019 – so this should also be the oldest version we support. And I think @pielstroem is also still on 14.04?). We should also pay attention to the `gcc` version. The current executable was built with `7.3.0`.

**Comment by severinsimmler** [comment] 2018-06-19 12:49
You can try `dariah-topics-explorer-0.1.6-linux-ubuntu-14.04.zip` from the release section – this was built on 14.04 and worked on a clean 14.04 Ubuntu, but fails on 18.04 :rage: (but this could also happen because of MATE, my desktop environment)... However, this is why we have now two archives for linux. Closing this now...

**Closed by severinsimmler** 2018-06-19 12:49 UTC
